# Generated by Django 3.2.8 on 2021-11-07 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_auto_20211107_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.customuser', verbose_name='Client'),
            preserve_default=False,
        ),
    ]
