## Purchasing products scenario

# sign in to the site
POST http://localhost/users-api/authentication/login/ HTTP/1.1
content-type: application/json

{
    "email": "admin@mail.com", 
    "password": "SECRET"
}

# create a new category
POST localhost/store-api/categories/ HTTP/1.1
Content-Type: application/json
Authorization: Token XXX

{
    "title": "New category"
}

# create a new product
POST localhost/store-api/products/ HTTP/1.1
Content-Type: application/json
Authorization: Token XXX

{
    "title": "New product",
    "description": "New product description",
    "price": "100",
    "size": "XL",
    "product_category": 1
}

# create a new order detail
POST localhost/store-api/order-details/ HTTP/1.1
Content-Type: application/json
Authorization: Token XXX

{
    "product": 1,
    "quantity": 2,
    "price": "100"
}

# create a new order
POST localhost/store-api/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Token XXX

{
    "client": 1,
    "details": [1],
    "is_closed": false
}

# close an order
PUT localhost/store-api/orders/1/ HTTP/1.1
Content-Type: application/json
Authorization: Token XXX

{
    "is_closed": true
}